name: Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: npm install, build, and deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        BRANCH: gh-pages
        FOLDER: build
        BUILD_SCRIPT: npm ci && npm run build
        BASE_BRANCH: develop
