name: Test

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install
      run: npm ci
    - name: lint
      run: CI=true npm run test:lint
      
  unit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install
      run: npm ci
    - name: lint
      run: CI=true npm run test:unit
  
  visual:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install
      run: npm ci
    - name: lint
      run: CI=true npm run test:visual:ci
